// actions
export const LOAD_STICKERS = 'LOAD_STICKERS';

//mutations
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_STICKERS = 'ADD_STICKERS';
export const REMOVE_STICKER = 'REMOVE_STICKER';
export const FINISH_STICKER = 'FINISH_STICKER';
export const UPDATE_STICKER = 'UPDATE_STICKER';
export const CREATE_STICKER = 'CREATE_STICKER';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const GET_NEW_STICKER_ID = 'GET_NEW_STICKER_ID';
